### ISSUE TITLE
instructions don't work

### ISSUE THREAD

**Issue by dmd** [pydicom/singularity-dicom#4]
The instructions at https://github.com/pydicom/dicom-containers/blob/master/getting-started/README.md do not work.

(1) They refer to commands that are no longer valid in Singularity, such as `singularity create`.

(2) Even if I try `singularity build dcm.img Singularity`, the build fails with:

```
Package libpng12-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libpng12-dev' has no installation candidate
FATAL:   post proc: exit status 100
FATAL:   While performing build: while running engine: exit status 255
```

**Comment by vsoch** [comment]
hey @dmd ! Yes the instructions were written a long time ago :) I'd be happy to update them for you. The missing library is likely because the miniconda base has updated it's base distro / the package is no longer available.

**Comment by dmd** [comment]
It looks like `libpng12-dev` is superceded by `libpng-dev` -- I've gotten a lot further (it's still building) after making that change.

**Comment by vsoch** [comment]
Great! I'll have a PR open soon to fix everything up including the instructions. Thanks for the pointer!

**Comment by dmd** [comment]
Build completed - the only change needed to the build spec is changing libpng12-dev to libpng-dev.

**Comment by vsoch** [comment]
Yes and ironically that change was already present in the Dockerfile! So it must have been found and fixed in one place but not the other.

I'll also be updating the dcmtk to a more recent release, and the images on Docker Hub.
