### ISSUE TITLE
Include dcm2niix?

### ISSUE THREAD

**Issue by dmd** [pydicom/singularity-dicom#6]
It might be nice if 

```
apt-get install -y dcm2niix
```

were added; I realize this is sort of out of scope, but it's an extremely common tool to want to run with `storescp --exec-on-eostudy`, so it would be useful to have *inside* the container

**Comment by vsoch** [comment]
Would you care to open a PR to add it? We have the Dockerfile under getting-started, and the Singularity recipe in the root.

**Comment by vsoch** [comment]
I'll just do it quickly, but I'll need to test the build fully first.
